### ISSUE TITLE
How to merge these rosbag

### ISSUE THREAD

**Issue by getupgetup** [TixiaoShan/Stevens-VLP16-Dataset#1]
Thanks a lot for sharing your dataset! Since these rosbags are seperated to pieces, I can't get the whole rosbag directly. What can I do to merge these bags to a completed one rosbag? Thank you~

**Comment by TixiaoShan** [comment]
@getupgetup 
You just need to play all the bags while running `rosbag record -a`. Then you get a whole bag.
