### ISSUE TITLE
IMU to Velodyne tranformation

### ISSUE THREAD

**Issue by ArashJavan** [TixiaoShan/Stevens-VLP16-Dataset#2]
Hi and thanks a lot for sharing your dataset, i would to use this dataset in my own project, but unfortunately i can not find the transformation between the  Lidar->Imu? Can you plz provide it to me!

Thanks and happy new year

**Comment by TixiaoShan** [comment]
Hi @ArashJavan 

Sorry, I don't have access to the robot anymore. In my previous implementations, I just assume Velodyne is in the same position as IMU. I know this is not technically correct, but the results seem to be good enough.
